version: '3'

services:
  proxy:
    image: h.proxy
    build:
      context: ./nginx
      # dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    #   # - ./nginx/conf.d:/etc/nginx/conf.d:ro
    #   # - /var/www/certbot:/var/www/certbot
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - h.api
      - h.gui
  # redis:
  #   image: redis
  #   restart: unless-stopped
  #   networks:
  #     - h.redis
  # postgres:
  #   image: postgres
  #   restart: unless-stopped
  #   networks:
  #     - h.postgres
  api:
    image: h.api
    build:
      context: ./api
      # dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - h.api
      - h.redis
      - h.postgres
    # depends_on:
    #   - redis
    #   - postgres
  # gui:
  #   image: nginx
  #   restart: unless-stopped
  #   networks:
  #     - h.gui

networks:
  h.redis:
  h.postgres:
  h.api:
  h.gui:
