plugins:
  - prettier
extends:
  - airbnb-base
  - plugin:node/recommended
  - prettier
rules:
  prettier/prettier: error
  no-unused-vars: warn
  no-console: warn
  no-process-exit: 'off'
  func-names: 'off'
