parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType:  module
plugins:
  - '@typescript-eslint'
  - prettier
extends:
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:node/recommended
  - airbnb-base
rules:
  prettier/prettier: warn
  no-unused-vars: warn
  no-console: warn
  no-process-exit: 'off'
  func-names: 'off'
