version: '3'
services:
  api:
    image: h.api.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    env_file:
      - ./.dev.env
    network_mode: host
#     ports:
#       - "$PORT:${PORT}"
#     networks:
#       - h.api.dev
# networks:
#   h.api.dev:
